apiVersion: syswe.me/v1alpha1
kind: PredictiveHorizontalPodAutoscaler
metadata:
  name: phpa-gbdt
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  syncPeriod: 10000
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  models:
    - type: GBDT
      name: gbdt-default
      perSyncPeriod: 1
      calculationTimeout: 25000
      gbdt:
        lookAhead: 20000
        historySize: 30
        lags: 8
