---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-syswe-me-syswe-me-v1alpha1-predictivehorizontalpodautoscaler
  failurePolicy: Fail
  name: mpredictivehorizontalpodautoscaler.kb.io
  rules:
  - apiGroups:
    - syswe.me.syswe.me
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - predictivehorizontalpodautoscalers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-syswe-me-syswe-me-v1alpha1-predictivehorizontalpodautoscaler
  failurePolicy: Fail
  name: vpredictivehorizontalpodautoscaler.kb.io
  rules:
  - apiGroups:
    - syswe.me.syswe.me
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - predictivehorizontalpodautoscalers
  sideEffects: None
