apiVersion: syswe.me/v1alpha1
kind: PredictiveHorizontalPodAutoscaler
metadata:
  name: simple-catboost
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
  models:
    - type: CatBoost
      name: simple-catboost
      catboost:
        lookAhead: 10000
        historySize: 30
        lags: 6

